Implements Localize
UniversalMediaServer/api pull request #1140
Opened 2022-12-08 23:06 UTC by SurfaceS

2022-12-20 21:51 UTC, SubJunk commented
@SurfaceS it would be good to get this up to date with main so we can see the tests pass

2022-12-20 21:59 UTC, SubJunk commented
It would also be good to add a test for the functionality

2022-12-20 22:00 UTC, SubJunk requested changes
This looks good. It would be good to add a test for the functionality too

2022-12-22 16:15 UTC, SurfaceS commented
obsolete by #1145

2022-12-22 16:15 UTC, closed without merging